INSERT INTO DISH (ID, TITLE, IMG_URL, DESCRIPTION)
VALUES (1, 'Dish 1', 'http://img', 'Dish Description 1');
INSERT INTO DISH (ID, TITLE, IMG_URL, DESCRIPTION)
VALUES (2, 'Dish 2', 'http://img', 'Dish Description 2');
INSERT INTO DISH (ID, TITLE, IMG_URL, DESCRIPTION)
VALUES (3, 'Dish 3', 'http://img', 'Dish Description 3');
INSERT INTO DISH (ID, TITLE, IMG_URL, DESCRIPTION)
VALUES (4, 'Dish 4', 'http://img', 'Dish Description 4');

INSERT INTO RESTAURANT (ID, TITLE, IMG_URL, DESCRIPTION)
VALUES (1, 'Restaurant 1', 'http://img', 'Restaurant Description 1');
INSERT INTO RESTAURANT (ID, TITLE, IMG_URL, DESCRIPTION)
VALUES (2, 'Restaurant 2', 'http://img', 'Restaurant Description 2');

INSERT INTO MENU (ID, RESTAURANT_ID, DISH_ID)
VALUES (1, 1, 1);
INSERT INTO MENU (ID, RESTAURANT_ID, DISH_ID)
VALUES (2, 1, 2);
INSERT INTO MENU (ID, RESTAURANT_ID, DISH_ID)
VALUES (3, 1, 3);
INSERT INTO MENU (ID, RESTAURANT_ID, DISH_ID)
VALUES (4, 1, 4);
INSERT INTO MENU (ID, RESTAURANT_ID, DISH_ID)
VALUES (5, 2, 1);
INSERT INTO MENU (ID, RESTAURANT_ID, DISH_ID)
VALUES (6, 2, 2);