DROP TABLE IF EXISTS MENU;
DROP TABLE IF EXISTS DISH;
DROP TABLE IF EXISTS RESTAURANT;

CREATE TABLE DISH
(
    ID          INT AUTO_INCREMENT PRIMARY KEY,
    TITLE       TINYTEXT                            NOT NULL,
    IMG_URL     TINYTEXT,
    DESCRIPTION TEXT,
    CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);


CREATE TABLE RESTAURANT
(
    ID          INT AUTO_INCREMENT PRIMARY KEY,
    TITLE       TINYTEXT                            NOT NULL,
    IMG_URL     TINYTEXT,
    DESCRIPTION TEXT,
    CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
);


CREATE TABLE MENU
(
    ID            INT AUTO_INCREMENT PRIMARY KEY,
    CREATED_AT    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    STATE         INT NOT NULL DEFAULT 1 COMMENT 'states: 1-available(default), 2-terminated, 3-invisible',
    TYPE          INT NOT NULL DEFAULT 1 COMMENT 'may be used to group menu dishes: 1-default',
    DISH_ID       INT NOT NULL,
    RESTAURANT_ID INT NOT NULL,
    CONSTRAINT DISH_ID_FK
        FOREIGN KEY (DISH_ID) REFERENCES DISH (ID)
            ON
                DELETE CASCADE
            ON
                UPDATE CASCADE,
    CONSTRAINT RESTAURANT_ID_FK
        FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANT (ID)
            ON
                DELETE CASCADE
            ON
                UPDATE CASCADE,
    CONSTRAINT DISH_ID_RESTAURANT_ID_U UNIQUE (DISH_ID, RESTAURANT_ID)
);
